//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace ExpenseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMS_DB
    {
        public int ExpenseId { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Please Provide Valid Date")] 
        public Nullable<System.DateTime> DateOfExpense { get; set; }
        [Required(ErrorMessage = "Please Select An ExpenseType")]
        public string ExpenseType { get; set; }
        [Required(ErrorMessage = "Please Provide Expense Amount")]
        public Nullable<int> Amount { get; set; }
    }
}
